### ISSUE TITLE
Wiki sample code

### ISSUE THREAD

**Issue by Hackmancoltaire** [rjwut/ian#1]
The ArtClientLib wiki had example code for creating a client and a proxy. Since IAN is slightly different, is  there sample code to do the same operations?

**Comment by rjwut** [comment]
Yes, I'll get that in soon.

**Comment by rjwut** [comment]
I haven't forgotten about this. I've recently made some changes in IAN (which I need to get pushed up to GitHub) which actually simplifies proxying.

**Comment by rjwut** [comment]
The `README.md` now gives updated source code illustrating how to create a proxy, and the new `ArtemisNetworkInterface.proxyTo()` method vastly simplifies proxying.
