### ISSUE TITLE
Multiple packets received simultaneously do not register correctly

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ian#11]
My app receives and parses CommsIncomingPackets to manage data on allies and docking stations, but sometimes it skips or ignores certain packets and doesn't update the data. My guess is that the packets are received at the same time and therefore only one of them is recognized.

**Comment by rjwut** [comment]
My best guess at the moment is that `CommsIncomingPacket` may actually contain more than one message. Are you able to reliably reproduce the problem? If so, can you implement the `Debugger` interface and pass it to `ArtemisNetworkInterface.attachDebugger()`, then check to see if `warn()` is invoked when the error happens? If so, you would likely see a message complaining about unread bytes.

In any case, capturing any error messages or packets related to the problem would help, and would instructions on how to reliably reproduce the problem.

**Comment by JordanLongstaff** [comment]
Actually, I've fixed the problem now. It seems like it actually had a different cause or a number of different causes including memory overflow or concurrent modification. This might still be an issue, but right now I'm not in a position to replicate it and I don't think it's going to happen.
