### ISSUE TITLE
Bad ObjectType when connecting to a server with a game in progress

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ian#12]
This doesn't always happen, but if I connect to a server that already has a simulation running, sometimes I'll get a "No ObjectType with this ID" error that disrupts the connection. My best guess is that it's simply an alignment issue, i.e. I joined a server that was in the middle of sending a packet.

**Comment by rjwut** [comment]
I doubt that's the problem; the server isn't going to send you a partial packet, and even if it did, you wouldn't get that error, because the partial packet wouldn't have begun with `0xdeadbeef`. Do you have a stack trace or any other information that could help me reproduce the problem?
