### ISSUE TITLE
Artemis 2.6.0 is out!

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ian#14]
There are some new features including Pirate ships and new types of fighters...you got some work to do! ;)

**Comment by rjwut** [comment]
Yup.  The only thing that should be needed to support those would be to update some of the enums. I haven't looked at it yet, but from what I can see, updates to `Faction`, `FactionAttribute`, `VesselAttribute` and maybe `SpecialAbility` would be all that would be required.

**Comment by JordanLongstaff** [comment]
I'm getting this error at CommsIncomingPacket.java, line 44:

"java.lang.ArrayIndexOutOfBoundsException: length=606; index=8912907"

I think there is in fact some new packet structure that also needs to be sorted out. I'd say it has something to do with the new revamped Comms screen features.

**Comment by rjwut** [comment]
Sorry, I meant the enum changes would be all that would be required for supporting the new ships. And on that note, could we separate these into individual issues? "Make it work for 2.6.0" is rather broad. So far, I've identified three different issues relating to 2.6.0:

- Support new faction and vessels.
- Support comms changes
- Support single-seat craft customization

**Comment by JordanLongstaff** [comment]
The protocol docs have recorded one change as of version 2.6: the bay number is now included in FighterBayStatusPackets.

**Comment by JordanLongstaff** [comment]
After some more investigating, it looks like the only change to CommsIncomingPackets isn't a new variable; instead, the "priority" field seems to have been reduced from an int to a short. Also, it's no longer a number between 0 and 8; instead, it's a bit field correspondent to the new categories of messages shown in the Comms screen; 1 = Alert, 2 = Side, 4 = Status, 8 = Player, etc.
