### ISSUE TITLE
server.isConnected() returning false when connected.

### ISSUE THREAD

**Issue by Hackmancoltaire** [rjwut/ian#2]
Just using the ArtClientLib example for a proxy when using:
server.setParsePackets(true);

and checking for:
server.isConnected();

it returns false, when setParsePackets is false, isConnected returns true. This worked properly in most recent ArtClientLib.

**Comment by rjwut** [comment]
Acknowledged, will investigate.

**Comment by rjwut** [comment]
I believe I have found the problem. I'm trying to get some last items cleaned up for an IAN release, so hopefully I'll have a resolution soon.

**Comment by rjwut** [comment]
[I just released IAN 3.1.0.](https://github.com/rjwut/ian/releases/tag/v3.1.0) Do you still experience problems with `isConnected()` on that version?
