### ISSUE TITLE
Server.java equals() method has a bug

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ian#20]
This line:

https://github.com/rjwut/ian/blob/b5ce857a7c7a309e67375ac2f86265d9f71eb240/src/main/java/com/walkertribe/ian/protocol/udp/Server.java#L102

The statement in that `if` check will never return true. It's supposed to check if the argument is a Server, but instead it checks if the calling object is a Server, which it necessarily is.

**Comment by rjwut** [comment]
Nice catch!
