### ISSUE TITLE
HeartbeatManager's mLost field never becomes true

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ian#24]
The `HeartbeatManager` class has a field called `mLost` that is declared and initialized as `false`. When it checks for a heartbeat, if it has not received one within the timeout period, it sends a `HeartbeatLostEvent`. However, in no part of `HeartbeatManager`'s code does `mLost` ever get set to `true`. Therefore, not only will many more unnecessary `HeartbeatLostEvent`s get sent, but if a new heartbeat gets received later, a `HeartbeatRegainedEvent` will not be sent.

**Comment by rjwut** [comment]
Nice catch! I've written a fix that I'll be committing soon.
