### ISSUE TITLE
No ObjectType with this ID

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ian#3]
I'm getting an error whenever player fighters are launched: "No ObjectType with this ID". The first errant ID was 63, so I modified the code to try to skirt around it, then it gave me the error again, but on 47 instead. It seems as if there's still some misalignment with the data from ObjectUpdatePackets.

**Comment by rjwut** [comment]
Sounds like it. Will investigate.

**Comment by rjwut** [comment]
Haven't forgotten about this. I've made numerous protocol fixes in the next version of IAN that I will hopefully get pushed to GitHub before long, so this is probably going to resolve this issue.

**Comment by rjwut** [comment]
[IAN 3.1.0 was just released.](https://github.com/rjwut/ian/releases/tag/v3.1.0) It should address the problems you were experiencing. Please let me know if it works for you.

**Comment by rjwut** [comment]
Since I haven't heard back, I'm closing this issue.

**Comment by JordanLongstaff** [comment]
Sorry I didn't reply sooner. Yes, my problem has been fixed, although I did recently get another "No ObjectType with this ID" error just recently under different circumstances. I don't know exactly why this happened and I have not been able to reproduce the error since, but if it happens again I'll let you know.
